export { NavigationTabs } from './NavigationTabs';
export { TabColors } from './TabColors';
export { TabCompare } from './TabCompare';
export { TabCookies } from './TabCookies'; 
export { TabImages } from './TabImages';
export { TabLinks } from './TabLinks';
export { TabScreenshot } from './TabScreenshot';
export { TabSeo } from './TabSeo';
export { TabTools } from './TabTools';